### PR TITLE
Add open source standard

### LINKED ISSUE #5: Make this open source to meet github recommended community standard.
Please see checklist here: https://github.com/indobenchmark/indonlu/community

- [x] Code of conduct
- [x] Issue templates
- [x] Pull request template
- [x] Adjust readme
- [x] Repository admins accept content reports

### PR DESCRIPTION
**Pull request by davidsetyanugraha**
Fixes #5 

## Proposed Changes
- [x] Add code of code of conduct (see CODE_OF_CONDUCT.md file). 
I am proposing the usage of Contributor Covenant. **Why?** this code of conduct has already been adopted by over 200,000 open source projects (such as React, Tensorflow, Salesforce OSS, Golang, etc).
- [x] Add badges to readme.
- [x] Add issue templates md file. See this [github doc](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/about-issue-and-pull-request-templates).
- [x] Add pull request template md file.  See this [github doc](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/about-issue-and-pull-request-templates).
- [x] Enable reported content for the repository.  see https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/managing-how-contributors-report-abuse-in-your-organizations-repository

### CODE REVIEW

**Comment by davidsetyanugraha** [comment]
@gentaiscool when you get a chance, please kindly check the changes. Thanks.

**Comment by davidsetyanugraha** [comment]
Need someone with admin access to enable this setting: https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/managing-how-contributors-report-abuse-in-your-organizations-repository

**Comment by gentaiscool** [comment]
> Need someone with admin access to enable this setting: https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/managing-how-contributors-report-abuse-in-your-organizations-repository

done. The commits look ok.

**Review by gentaiscool — COMMENTED** [review]
The PR is ready to go!

**Pull request merged**
